### PR TITLE
[WIP] Building multi nav from scratch

### PR DESCRIPTION
**Pull request by deborahchua**
This has been a fiddly process, but so far I have managed to restructure the `/career-path` section to use the mult-nav functionality.

Couple of things I have been stuck on
- separate pages (About, Resources, Contributing) are still listed within the left nav of /career-path. I haven't figured out what I need to do to fix this
- In the `Resources` section, some of the `<h2>`'s aren't rendering as tags. I've noticed this seems to happen when it is appearing just after some bullet points.

Current layout:
screen shot 2018-10-05 at 16 09 36

Updated layout:
screen shot 2018-10-05 at 16 10 50

### CODE REVIEW

**Comment by deborahchua** [comment]
@MatMoore would you be able to pull down this branch and see if this is what we had in mind?
I've had to do a lot of renaming and moving around, but I've checked to see that all the files have been kept. Any that currently aren't under a specific section live under `/source/resources/documentation/other`.

**Comment by MatMoore** [comment]
Cool, I just got back from holiday but I'll try and take a look tomorrow 🐌

**Comment by MatMoore** [comment]
I tried it out locally and the multi level nav is working 🙂

It looks like a step in the right direction, but seems like there's a few issues to work out before merging.

For some reason search doesn't work for me (at least when running locally). I'm just going to ignore that for now though as I think the structure is more important than working search. Also, I noticed the contributing guide seems to have disappeared - was that intentional? There's a [config in the template for showing a contribution banner](https://alphagov.github.io/tech-docs-manual/#show-contribution-banner) so maybe we can rework that in a follow up PR.

I had a go at solving the first problem and pushed up a new commit - I think the issue was that the main index was actually the career path index. I switched it around so that the main index is the about section, and then I created a subsection for the career path.

What do you think of this top level structure? It needs a bit more work as all the header links are broken, but is there anything missing there that shouldn't be nested in another section? Maybe we could do some guerrilla usability testing as well to test the structure makes sense to people.

I haven't investigated the issue with rendering h2s but it seems we could solve it by splitting up the pages instead of including them all on one page via partials. I don't think it makes sense to render the whole lot together because if you're reading this section you're probably only interested in a particular subject.

The competencies also get rendered together, which is maybe less of issue than with the resources but it seems like an overwhelming amount of content to me. It's hard to see where one competency ends and another begins because there are a lot of header levels and some competencies are just a header with no content yet. I'm hoping we can just split up these pages and have an index page for them without breaking the sidebar navigation 🤞

**Comment by MatMoore** [comment]
Hi @deborahchua do you have any thoughts about how we get this merged into master? Since it has diverged a lot I'm wondering if it's easier to cherry pick stuff into this branch and make it the new master rather than merge normally?

**Comment by deborahchua** [comment]
@MatMoore I've reviewed the changes and added contributions that were missed. Hopefully this should be ready now 🤞

**Comment by MatMoore** [comment]
Cool, I'll review that tomorrow morning and if there are no problems I'll just force push this into master 💥

**Pull request merged**
