### PR TITLE
Add user story template

### PR DESCRIPTION
**Pull request by deborahchua**
To help understand whether a task is well defined, it might be a good idea to have a template of a well defined story. Although most teams have a template to fill in new stories they may not be publicly available.

### CODE REVIEW

**Comment by MatMoore** [comment]
I think this needs a bit of context to explain what this is and why it might be useful. I'd emphasise this is just an example and not a standard of any kind...

I think the service manual is worth linking to as well https://www.gov.uk/service-manual/agile-delivery/writing-user-stories

**Comment by deborahchua** [comment]
I was thinking we could link to this template from where we mention 'well defined stories' in the [leading stories competency](https://github.com/alphagov/gds-tech-learning-pathway/blob/master/career-path/competencies/leading-on-stories.md).

It was also discussed in this issue: https://github.com/alphagov/gds-tech-learning-pathway/issues/40

Maybe we need a separate file which covers well defined stories in more detail, with some examples showing what this could look like?

**Comment by Davidslv** [comment]
I think we should add this as an example - that's what this is.
But this PR is incomplete without the context, @deborahchua you should create a link after "well defined stories". Something like

`well defined stories [see an example](link)`

**Comment by deborahchua** [comment]
Thanks @Davidslv and @MatMoore , I have linked to it from the competency 🍰

**Comment by Davidslv** [comment]
Closes #40

**Pull request merged**
